---
- name: Reload keyd
  ansible.builtin.systemd:
    name: keyd.service
    state: restarted
  become: true

- name: Rebuild initramfs
  ansible.builtin.command:
    cmd: mkinitcpio -P
  become: true
